version: '2'

services:
  main:
    image: github
    build:
      context: ./
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    # can not work on mac
    # network_mode: host
    volumes:
      - .:/host
    working_dir: /host
    env_file: .env

  dev:
    extends: main
    container_name: github
    ports:
      - 10000:10000
      - 10001:10001
