version: '2'

services:
  main:
    container_name: github
    image: github
    build:
      context: ./
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    # can not work on mac
    # network_mode: host
    ports:
      - 10000:10000
    volumes:
      - .:/host
    working_dir: /host
    env_file: .env
