version: '2'

services:
  main:
    container_name: github
    image: test1
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    ports:
        - 10000:8080
    volumes:
        - .:/host
    working_dir: /host
    environment:
      NODE_PATH: /app/node_modules
