version: '2'

services:
  main:
    container_name: github
    image: github
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    network_mode: host
    volumes:
        - .:/host
    working_dir: /host
    environment:
      NODE_PATH: /app/node_modules
